@local_ftsprocurement = http://localhost:8080/ftsprocurement

@ftsprocurement = https://ftsprocurement.lakeatts.co.ke:8443/ftsprocurement


@ftsadmin = https://ftsadmin.lakeatts.co.ke:8443/ftsadministration


@local_ftsadmin = http://localhost:8080/ftsadministration

### 1. CREATE WORKFLOW
POST {{ftsprocurement}}/workflows
Content-Type: application/json

{
  "id": 1,
  "name": "SDA Expense Approval",
  "denominationId": 8,
  "organisationLevel": 7,
  "active": true
}


### 1. GET DATA
GET {{ftsprocurement}}/workflows


### 1. UPDATE WORKFLOW
PUT {{local_ftsprocurement}}/workflows
Content-Type: application/json

{
  "id": 1,
  "name": "SDA-Local-Church Expense Approval",
  "denominationId": 8,
  "organisationLevel": 7,
  "active": true
}

### 2. CREATE WORKFLOW STEPS  Step 1 → Department Approval
POST {{local_ftsprocurement}}/workflow-steps
Content-Type: application/json

{
  "id": 1,
  "workflowId": 1,
  "stepOrder": 1,
  "stepName": "Department Approval",
  "approvalMode": "SINGLE",
  "thresholdValue": 1,
  "minAmount": 0,
  "maxAmount": 50000,
  "isFinalStep": false
}

### Step 2 → Church Board
POST {{local_ftsprocurement}}/workflow-steps
Content-Type: application/json

{
  "id": 2,
  "workflowId": 1,
  "stepOrder": 2,
  "stepName": "Church Board Approval",
  "approvalMode": "MAJORITY",
  "thresholdValue": 0.6,
  "minAmount": 0,
  "maxAmount": 200000,
  "isFinalStep": false
}

### Step 2 → Get Church Board
GET {{ftsprocurement}}/workflow-steps

###Step 3 → Church Members (Final)
POST {{ftsprocurement}}/workflow-steps
Content-Type: application/json

{
  "id": 3,
  "workflowId": 1,
  "stepOrder": 3,
  "stepName": "Church Business Meeting",
  "approvalMode": "MAJORITY",
  "thresholdValue": 0.7,
  "minAmount": 0,
  "maxAmount": null,
  "isFinalStep": true
}
### 3. LEADERSHIP ASSIGNMENTS
POST {{local_ftsprocurement}}/leadership-assignments
Content-Type: application/json

{
  "id": 1,
  "designation": "Treasurer",
  "denominationId": 1,
  "personnelId": 1001,
  "organisationId": 87000029,
  "active": true
}

### Second option
POST {{local_ftsprocurement}}/leadership-assignments
Content-Type: application/json

{
  "id": 2,
  "designation": "Elder",
  "denominationId": 1,
  "personnelId": 1002,
  "organisationId": 87000029,
  "active": true
}
###✅ 4. DEPARTMENT PROJECT
POST {{local_ftsprocurement}}/department-projects
Content-Type: application/json

{
  "id": 1,
  "organisationId": 87000029,
  "departmentName": "Youth Department",
  "projectName": "Youth Camp 2026",
  "description": "Annual youth spiritual camp",
  "createdBy": 1001
}


###✅ 4. GET DEPARTMENT PROJECT
GET {{ftsprocurement}}/department-projects/by-organisation?organisationId=87000029


###✅ 4. DEPARTMENT PROJECT
PUT {{local_ftsprocurement}}/department-projects
Content-Type: application/json

{
  "id": 1,
  "organisationId": 87000029,
  "departmentName": "Youth Department",
  "projectName": "Youth Camp 2026",
  "description": "Annual Bible Study Retreat",
  "createdBy": 1001
}


###✅ 5. PROJECT BUDGET ITEMS
POST {{local_ftsprocurement}}/project-budget-items/add
Content-Type: application/json

{
  "id": 1,
  "projectId": 1,
  "itemName": "Transport",
  "quantity": 1,
  "unitCost": 50000
}

###
PUT {{local_ftsprocurement}}/project-budget-items/add
Content-Type: application/json

{
  "id": 2,
  "projectId": 1,
  "itemName": "Food",
  "quantity": 100,
  "unitCost": 300
}


### GET ALL PROJECT ITEMS
GET {{ftsprocurement}}/project-budget-items/all




### GET ALL PROJECT ITEMS
GET {{ftsprocurement}}/project-budget-items/by-project?projectId=1




###✅ 6. CREATE APPROVAL REQUEST 👉 Total = 50,000 + 30,000 = 80,000
POST {{local_ftsprocurement}}/approval-requests
Content-Type: application/json

{
  "id": 1,
  "workflowId": 1,
  "workflowStepId": 1,
  "referenceNumber": "REQ-001",
  "organisationId": 87000029,
  "amount": 80000,
  "currentStepId": 1,
  "createdBy": 1001,
  "departmentName": "Youth Department",
  "projectName": "Youth Camp 2026"
}


###✅ 7. STEP INSTANCE
POST {{local_ftsprocurement}}/approval-step-instances
Content-Type: application/json

{
  "id": 1,
  "requestId": 1,
  "stepId": 1,
  "status": "PENDING"
}


###✅ 8. APPROVAL VOTES
Treasurer approves
POST {{local_ftsprocurement}}/approval-votes
Content-Type: application/json

{
  "id": 1,
  "requestId": 1,
  "stepId": 1,
  "voterId": 1001,
  "designation": "Treasurer",
  "organisationId": 87000029,
  "vote": "APPROVED",
  "weight": 1,
  "comment": "Looks good"
}


###Elder approves
POST {{local_ftsprocurement}}/approval-votes
Content-Type: application/json

{
  "id": 2,
  "requestId": 1,
  "stepId": 1,
  "voterId": 1002,
  "designation": "Elder",
  "organisationId": 87000029,
  "vote": "APPROVED",
  "weight": 1,
  "comment": "Approved"
}

 
    
###Get by step  with request id and step id
GET {{ftsprocurement}}/approval-votes/by-step?requestId=1&stepId=1



    
###Get by step  with request id and step id and vote
GET {{ftsprocurement}}/approval-votes/weight?requestId=1&stepId=1&vote=APPROVED

 
###✅ 9. APPROVAL ACTION (SYSTEM DECISION)
POST {{local_ftsprocurement}}/approval-actions
Content-Type: application/json

{
  "id": 1,
  "requestId": 1,
  "stepId": 1,
  "designation": "SYSTEM",
  "denominationId": 1,
  "userId": null,
  "action": "APPROVED",
  "weight": 1,
  "comment": "Step approved after reaching threshold"
}